DIM dyear,dmonth,ddate,dhour,dminute,dsecond AS INTEGER
DIM erweima,erweima1,erweima2,erweima3 AS INTEGER
DIM erweima4,erweima5,erweima6,run1,zhuye AS INTEGER
DIM tiaosu AS INTEGER
erweima=1
run1=2
zhuye=3
tiaosu=4
cangku=5
fanhui2=6
fanhui3=7
fanhui4=8
fanhui5=9
fanhui6=17

erweima1=11
erweima2=12
erweima3=13
erweima4=14
erweima5=15
erweima6=16
fanhui=10

dyear=25
dmonth=26
ddate=27
dhour=28
dminute=29
dsecond=30
